import { Team } from '../enums/Team.js';
import type { GenericObject } from '../types/GenericObject.js';

export const coversTeam: GenericObject = {
   [Team.ARI]: 'ARI',
   [Team.ATL]: 'ATL',
   [Team.BAL]: 'BAL',
   [Team.BOS]: 'BOS',
   [Team.CHC]: 'CHC',
   [Team.CHW]: 'CHW',
   [Team.CIN]: 'CIN',
   [Team.CLE]: 'CLE',
   [Team.COL]: 'COL',
   [Team.DET]: 'DET',
   [Team.HOU]: 'HOU',
   [Team.KCR]: 'KC',
   [Team.LAA]: 'LAA',
   [Team.LAD]: 'LAD',
   [Team.MIA]: 'MIA',
   [Team.MIL]: 'MIL',
   [Team.MIN]: 'MIN',
   [Team.NYM]: 'NYM',
   [Team.NYY]: 'NYY',
   [Team.OAK]: 'OAK',
   [Team.PHI]: 'PHI',
   [Team.PIT]: 'PIT',
   [Team.SDP]: 'SD',
   [Team.SEA]: 'SEA',
   [Team.SFG]: 'SF',
   [Team.STL]: 'STL',
   [Team.TBR]: 'TB',
   [Team.TEX]: 'TEX',
   [Team.TOR]: 'TOR',
   [Team.WSN]: 'WAS',
}