export enum Venue {
   'Bank One Ballpark' = 14,
   'Busch Stadium II' = 11,
   'Cinergy Field' = 5,
   'Edison Field' = 2,
   'Enron Field' = 17,
   'Hubert H. Humphrey Metrodome' = 7,
   'Kauffman Stadium' = 18,
   'Network Associates Coliseum' = 10,
   'Oriole Park at Camden Yards' = 4,
   'Pro Player Stadium' = 6,
   'Safeco Field' = 16,
   'Shea Stadium' = 9,
   'SkyDome' = 13,
   'Stade Olympique' = 8,
   'The Ballpark in Arlington' = 12,
   'Three Rivers Stadium' = 15,
   'Tokyo Dome' = 1,
   'Turner Field' = 3,
}